### ISSUE TITLE
URL title not working for some URLs

### ISSUE THREAD

**Issue by vranki** [vranki/hemppa#29]
For example:

https://www.iltalehti.fi/kotimaa/a/ebc20dd4-700d-4c98-9cc6-32d50f7dc55c

**Comment by tswfi** [comment]
For that url the reason was that the bot was not set to spam the channel

![image](https://user-images.githubusercontent.com/1352132/73343727-c1f17100-4289-11ea-8039-59ff876ee627.png)

the other url that really fails is this:

https://www.ilmailuliitto.fi/2020/01/23/uuden-jasenrekisterin-kayttoonotto-viivastyy-edelleen/

and the reason for the fail is:

```
import httpx 
from lxml.html.soupparser import fromstring
r = httpx.get("https://www.ilmailuliitto.fi/2020/01/23/uuden-jasenrekisterin-kayttoonotto-viivastyy-edelleen/")         
titleelem = fromstring(r.text).find(".//head/title")       

ValueError: Invalid PI name 'b'xml''
```

I will still change the url module to use beatuful soup 4 for parsing..
