### ISSUE TITLE
Download room history as text

### ISSUE THREAD

**Issue by vranki** [vranki/hemppa#96]
Add command to download room history as text or other formats. Allow limiting to avoid downloading too much. Upload the resulting file to the room.

**Comment by ptman** [comment]
This may cause a problem for rooms with "history visible to members since they joined".

1. bot joins
2. chatting
3. user joins
4. someone requests history
5. bot gets all the history it can
6. bot posts history to room
7. user can get history from before they joined by downloading the history posted by bot

**Comment by vranki** [comment]
Yes, but if you replace bot with another user, the another user can anyway give the history to newly joined user. I wouldn't use that option for security if users are not trusted.

**Comment by vranki** [comment]
Element (web/desktop) implemented this feature so no longer needed in Hemppa.
